DROP SCHEMA IF EXISTS DER;
CREATE SCHEMA DER;

USE jwt;
SHOW TABLES;

CREATE TABLE clientes (
  id INT NOT NULL AUTO_INCREMENT,
  nome VARCHAR(255) NOT NULL,
  nick_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  telefone VARCHAR(255) NOT NULL,
  senha VARCHAR(255) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY email (email)
);



LOAD DATA INFILE 'C:\\Users\\guilherme_faccin\\Downloads\\Anexos\\DadosBanco\\usuarios.csv'
INTO TABLE clientes
FIELDS TERMINATED BY ','LINES
TERMINATED BY '\n'
IGNORE 1 ROWS;

SELECT * FROM clientes;